name: Run French Converter

on:
  push:
    branches: [ main ] # Runs every time you push code to the main branch
  workflow_dispatch: # Allows you to run it manually with a button click

permissions:
  contents: write
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests
        python -m pip install --upgrade pip
        pip install requests deep-translator

    - name: Run converter script
      run: python converter.py

    - name: Commit and push generated JSON
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@://github.com"
        git add french_frequency.json
        git commit -m "Automated: Updated French vocabulary JSON" || exit 0
        git push || (git pull --rebase && git push)
